---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

---
resources:
  - name: add-number
    type: git
    source: &repo-source
      uri: git@github.com:obasajujoshua31/test-concorse.git
      branch: main
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install dependencies
    plan:
      - get: add-number
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: add-number
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - task: run the test suite
        file: run_tests.yml

